//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filmler
    {
        public int FilmId { get; set; }
        public string Tur { get; set; }
        public string FilmAd { get; set; }
        public string Konu { get; set; }
        public string Yonetmen { get; set; }
        public string Basrol { get; set; }
        public string Senarist { get; set; }
        public string Dil { get; set; }
        public Nullable<System.DateTime> VizyonTarihi { get; set; }
        public string Sure { get; set; }
        public string YetiskinlikDuzeyi { get; set; }
        public string IMDb { get; set; }
    }
}
