//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeller
    {
        public int PersonelId { get; set; }
        public string KullaniciAd { get; set; }
        public string Sifre { get; set; }
        public string AdSoyad { get; set; }
        public Nullable<System.DateTime> DogumGunu { get; set; }
        public string Mail { get; set; }
        public string Gsm { get; set; }
        public string Adres { get; set; }
        public string CV { get; set; }
    }
}
