//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salonlar
    {
        public int SalonId { get; set; }
        public string SalonAd { get; set; }
        public string SalonFormat { get; set; }
        public string FilmSeans { get; set; }
        public string FilmTur { get; set; }
        public string FilmAd { get; set; }
        public string Sure { get; set; }
        public string FilmFormat { get; set; }
        public string DilFormat { get; set; }
    }
}
