//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinema
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SinemaEntitiess : DbContext
    {
        public SinemaEntitiess()
            : base("name=SinemaEntitiess")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Biletler> Biletler { get; set; }
        public virtual DbSet<Filmler> Filmler { get; set; }
        public virtual DbSet<Personeller> Personeller { get; set; }
        public virtual DbSet<SalonA> SalonA { get; set; }
        public virtual DbSet<SalonB> SalonB { get; set; }
        public virtual DbSet<SalonC> SalonC { get; set; }
        public virtual DbSet<Salonlar> Salonlar { get; set; }
    }
}
